export const CLOSURE_PROOF_STATUSES = [
  'fixed_in_release',
  'fixed_after_release',
  'fixed_in_later_release',
  'fixed_not_in_scored_releases',
  'fixed_after_latest_release',
  'fixed_skipped_by_later_releases',
  'duplicate_to_fixed_in_release',
  'duplicate_to_open_canonical',
  'duplicate_to_closed_canonical',
  'duplicate_to_non_actionable_canonical',
  'duplicate_to_known_not_in_release_canonical',
  'duplicate_to_open_pr_canonical',
  'duplicate_to_unverified_closed_canonical',
  'duplicate_to_closed_canonical_missing_proof',
  'duplicate_to_fixed_after_release',
  'duplicate_with_release_fix_proof',
  'superseded_to_open_pr',
  'duplicate_with_open_pr_context',
  'duplicate_related_closed_unmerged_pr_context',
  'duplicate_related_merged_pr_not_reachable_context',
  'duplicate_related_merged_pr_reachable_context_without_fix_credit',
  'duplicate_related_merged_pr_reachability_unknown',
  'duplicate_related_pr_without_release_fix',
  'canonical_cycle_or_self_reference',
  'duplicate_or_superseded',
  'not_planned',
  'admin_not_planned_unverified',
  'admin_not_planned_no_context',
  'not_planned_with_release_fix_proof',
  'not_planned_fixed_after_release',
  'not_planned_direct_fix_commit_reachability_unknown',
  'not_planned_with_open_pr_context',
  'not_planned_linked_pr_not_merged',
  'not_planned_related_closed_unmerged_pr_context',
  'not_planned_related_merged_pr_not_reachable_context',
  'not_planned_related_merged_pr_reachable_context_without_fix_credit',
  'not_planned_related_merged_pr_reachability_unknown',
  'not_planned_related_pr_without_release_fix',
  'already_present_claim',
  'main_only_claim',
  'reporter_replaced',
  'reporter_withdrawn',
  'reporter_self_closed',
  'repro_requested',
  'insufficient_info',
  'no_code_proof',
  'linked_closing_pr_reachability_unknown',
  'linked_closing_pr_not_merged',
  'linked_closing_pr_open',
  'linked_closing_pr_closed_unmerged',
  'external_repo_closing_pr_unscored',
  'related_open_pr_context',
  'related_closed_unmerged_pr_context',
  'related_merged_pr_not_reachable_context',
  'related_merged_pr_reachable_context_without_fix_credit',
  'related_merged_pr_reachability_unknown',
  'related_pr_without_release_fix',
  'direct_fix_commit_reachability_unknown',
  'closed_without_release_fix_proof',
  'no_timeline_event',
  'non_bug_fixed_in_release',
  'non_bug_fixed_after_release',
  'non_bug_direct_fix_commit_reachability_unknown',
  'non_bug_fixed_in_later_release',
  'non_bug_fixed_not_in_scored_releases',
  'non_bug_fixed_after_latest_release',
  'non_bug_fixed_skipped_by_later_releases',
  'non_bug_linked_without_merge',
  'non_bug_linked_pr_open',
  'non_bug_linked_pr_closed_unmerged',
  'non_bug_duplicate_to_fixed_in_release',
  'non_bug_duplicate_to_open_canonical',
  'non_bug_duplicate_to_closed_canonical',
  'non_bug_duplicate_to_closed_canonical_missing_proof',
  'non_bug_duplicate_to_fixed_after_release',
  'non_bug_superseded_to_open_pr',
  'non_bug_duplicate_with_open_pr_context',
  'non_bug_duplicate_related_closed_unmerged_pr_context',
  'non_bug_duplicate_related_merged_pr_not_reachable_context',
  'non_bug_duplicate_related_merged_pr_reachable_context_without_fix_credit',
  'non_bug_duplicate_related_merged_pr_reachability_unknown',
  'non_bug_duplicate_related_pr_without_release_fix',
  'non_bug_duplicate_or_superseded',
  'non_bug_not_actionable',
  'non_bug_neutral',
  'unknown',
] as const;

export type ClosureProofStatus = (typeof CLOSURE_PROOF_STATUSES)[number];

export const CLOSURE_RISK_DISPOSITIONS = [
  'credited_release_fix',
  'resolved_by_canonical_release_fix',
  'resolved_by_release_fix_proof',
  'known_not_in_release',
  'open_canonical_risk',
  'unsupported_closure_claim',
  'neutral_or_non_actionable',
  'missing_evidence',
] as const;

export type ClosureRiskDisposition = (typeof CLOSURE_RISK_DISPOSITIONS)[number];

export const CLOSURE_RISK_DISPOSITION_BY_STATUS: Record<ClosureProofStatus, ClosureRiskDisposition> = {
  fixed_in_release: 'credited_release_fix',
  duplicate_to_fixed_in_release: 'resolved_by_canonical_release_fix',
  duplicate_with_release_fix_proof: 'resolved_by_release_fix_proof',
  not_planned_with_release_fix_proof: 'resolved_by_release_fix_proof',
  fixed_after_release: 'known_not_in_release',
  fixed_in_later_release: 'known_not_in_release',
  fixed_not_in_scored_releases: 'known_not_in_release',
  fixed_after_latest_release: 'known_not_in_release',
  fixed_skipped_by_later_releases: 'known_not_in_release',
  main_only_claim: 'known_not_in_release',
  duplicate_to_fixed_after_release: 'known_not_in_release',
  not_planned_fixed_after_release: 'known_not_in_release',
  not_planned_direct_fix_commit_reachability_unknown: 'missing_evidence',
  duplicate_to_open_canonical: 'open_canonical_risk',
  superseded_to_open_pr: 'open_canonical_risk',
  duplicate_with_open_pr_context: 'open_canonical_risk',
  duplicate_related_closed_unmerged_pr_context: 'unsupported_closure_claim',
  duplicate_related_merged_pr_not_reachable_context: 'unsupported_closure_claim',
  duplicate_related_merged_pr_reachable_context_without_fix_credit: 'unsupported_closure_claim',
  duplicate_related_merged_pr_reachability_unknown: 'unsupported_closure_claim',
  duplicate_related_pr_without_release_fix: 'unsupported_closure_claim',
  not_planned_with_open_pr_context: 'open_canonical_risk',
  duplicate_to_open_pr_canonical: 'open_canonical_risk',
  duplicate_to_closed_canonical: 'unsupported_closure_claim',
  duplicate_to_non_actionable_canonical: 'neutral_or_non_actionable',
  duplicate_to_known_not_in_release_canonical: 'known_not_in_release',
  duplicate_to_unverified_closed_canonical: 'unsupported_closure_claim',
  duplicate_to_closed_canonical_missing_proof: 'missing_evidence',
  canonical_cycle_or_self_reference: 'unsupported_closure_claim',
  duplicate_or_superseded: 'unsupported_closure_claim',
  already_present_claim: 'unsupported_closure_claim',
  admin_not_planned_unverified: 'unsupported_closure_claim',
  admin_not_planned_no_context: 'unsupported_closure_claim',
  not_planned_linked_pr_not_merged: 'unsupported_closure_claim',
  not_planned_related_closed_unmerged_pr_context: 'unsupported_closure_claim',
  not_planned_related_merged_pr_not_reachable_context: 'unsupported_closure_claim',
  not_planned_related_merged_pr_reachable_context_without_fix_credit: 'unsupported_closure_claim',
  not_planned_related_merged_pr_reachability_unknown: 'unsupported_closure_claim',
  not_planned_related_pr_without_release_fix: 'unsupported_closure_claim',
  repro_requested: 'unsupported_closure_claim',
  insufficient_info: 'unsupported_closure_claim',
  no_code_proof: 'unsupported_closure_claim',
  linked_closing_pr_reachability_unknown: 'missing_evidence',
  linked_closing_pr_not_merged: 'unsupported_closure_claim',
  linked_closing_pr_open: 'open_canonical_risk',
  linked_closing_pr_closed_unmerged: 'unsupported_closure_claim',
  external_repo_closing_pr_unscored: 'unsupported_closure_claim',
  related_open_pr_context: 'open_canonical_risk',
  related_closed_unmerged_pr_context: 'unsupported_closure_claim',
  related_merged_pr_not_reachable_context: 'unsupported_closure_claim',
  related_merged_pr_reachable_context_without_fix_credit: 'unsupported_closure_claim',
  related_merged_pr_reachability_unknown: 'unsupported_closure_claim',
  related_pr_without_release_fix: 'unsupported_closure_claim',
  direct_fix_commit_reachability_unknown: 'missing_evidence',
  closed_without_release_fix_proof: 'unsupported_closure_claim',
  non_bug_neutral: 'neutral_or_non_actionable',
  not_planned: 'neutral_or_non_actionable',
  reporter_replaced: 'neutral_or_non_actionable',
  reporter_withdrawn: 'neutral_or_non_actionable',
  reporter_self_closed: 'neutral_or_non_actionable',
  non_bug_fixed_in_release: 'neutral_or_non_actionable',
  non_bug_fixed_after_release: 'neutral_or_non_actionable',
  non_bug_direct_fix_commit_reachability_unknown: 'neutral_or_non_actionable',
  non_bug_fixed_in_later_release: 'neutral_or_non_actionable',
  non_bug_fixed_not_in_scored_releases: 'neutral_or_non_actionable',
  non_bug_fixed_after_latest_release: 'neutral_or_non_actionable',
  non_bug_fixed_skipped_by_later_releases: 'neutral_or_non_actionable',
  non_bug_linked_without_merge: 'neutral_or_non_actionable',
  non_bug_linked_pr_open: 'neutral_or_non_actionable',
  non_bug_linked_pr_closed_unmerged: 'neutral_or_non_actionable',
  non_bug_duplicate_to_fixed_in_release: 'neutral_or_non_actionable',
  non_bug_duplicate_to_open_canonical: 'neutral_or_non_actionable',
  non_bug_duplicate_to_closed_canonical: 'neutral_or_non_actionable',
  non_bug_duplicate_to_closed_canonical_missing_proof: 'neutral_or_non_actionable',
  non_bug_duplicate_to_fixed_after_release: 'neutral_or_non_actionable',
  non_bug_superseded_to_open_pr: 'neutral_or_non_actionable',
  non_bug_duplicate_with_open_pr_context: 'neutral_or_non_actionable',
  non_bug_duplicate_related_closed_unmerged_pr_context: 'neutral_or_non_actionable',
  non_bug_duplicate_related_merged_pr_not_reachable_context: 'neutral_or_non_actionable',
  non_bug_duplicate_related_merged_pr_reachable_context_without_fix_credit: 'neutral_or_non_actionable',
  non_bug_duplicate_related_merged_pr_reachability_unknown: 'neutral_or_non_actionable',
  non_bug_duplicate_related_pr_without_release_fix: 'neutral_or_non_actionable',
  non_bug_duplicate_or_superseded: 'neutral_or_non_actionable',
  non_bug_not_actionable: 'neutral_or_non_actionable',
  no_timeline_event: 'missing_evidence',
  unknown: 'missing_evidence',
};

export const CLOSURE_RISK_DISPOSITION_WEIGHT: Record<ClosureRiskDisposition, number> = {
  credited_release_fix: 0,
  resolved_by_canonical_release_fix: 0,
  resolved_by_release_fix_proof: 0,
  known_not_in_release: 1,
  open_canonical_risk: 1.2,
  unsupported_closure_claim: 0.8,
  neutral_or_non_actionable: 0,
  missing_evidence: 1.5,
};

export function closureRiskDisposition(status: string): ClosureRiskDisposition {
  return CLOSURE_RISK_DISPOSITION_BY_STATUS[status as ClosureProofStatus] ?? 'missing_evidence';
}

export function closureRiskDispositionLabel(disposition: string): string {
  return ({
    credited_release_fix: 'credited release fix',
    resolved_by_canonical_release_fix: 'resolved by canonical release fix',
    resolved_by_release_fix_proof: 'resolved by release fix proof',
    known_not_in_release: 'known not in this tag',
    open_canonical_risk: 'still-open canonical/PR risk',
    unsupported_closure_claim: 'unsupported closure/admin claim',
    neutral_or_non_actionable: 'not-scored/non-actionable closure',
    missing_evidence: 'missing proof evidence',
  } as Record<string, string>)[disposition] ?? String(disposition ?? 'unknown closure risk');
}

export function closureRiskWeightLabel(weight: unknown): string {
  return typeof weight === 'number' && Number.isFinite(weight)
    ? `risk ${Math.round(weight * 100) / 100}`
    : 'risk unknown';
}
